### ISSUE TITLE
Crion damage

### ISSUE THREAD

**Issue by LordHISKI** [InsideEarth2150/IEO-Updates#19] opened 2021-02-24 13:38 UTC
Crion is doing energy or kinetic dmg?
Because it ignore shield AND Armor
pls change the damage type to one of it, it shouldn't ignore both.

**Comment by Animal-UK** [comment] 2021-02-24 15:19
Please vote here: https://linkto.run/p/DWV6BU62

**Comment by Animal-UK** [comment] 2021-03-07 15:54
LCWHC1 - typeOfDamage: #damageNoArmourNoShield > #damageNoArmourKillShield

**Comment by Skeltek** [comment] 2021-03-12 10:47
Wasn't the whole point of Crion having shortest range, being a fragile unit, no area of effect and being weakest the tradeoff of ignoring shields?

**Comment by Skeltek** [comment] 2021-03-15 22:04
LC Crion damage: 500, range 20, no AoE
ED Artillery damage: 1250, range: 45, AoE range: 3 (can hit up to 37 units hit)
UCS Artillery damage: 2000, range: 51, AoE range: 3

Crion is highly immobile, misses most shots, slow to turn and a sitting very fragile duck. Production time and costs are high.
It deals friendly fire easily, research time is high and long and hidden behind underused heavy sonic. Even with an army in front, they usualy get overrun by enemies, before they can earn their worth.

The shield penetration is the only halfway good feature about it and as far as I know the feature was introduced just for this unit. No other energy weapon I know of penetrates shields. It'S like that on purpose.

**Comment by Animal-UK** [comment] 2021-03-22 10:54
this has been moved to 2.2.3 release to allow for further discussion and hopeful agreement.

@Skeltek Is there any formal lore/back that supports your "shield penetration" statement?

**Comment by koniecpolski** [comment] 2021-03-22 11:03
> shield penetration formal lore/back
:) that's entire **Earth 2150 Escape from the Blue Planet** game. Crion's cannon worked that way since the very origin.

**Comment by Skeltek** [comment] 2021-03-22 16:15
> 
> 
> this has been moved to 2.2.3 release to allow for further discussion and hopeful agreement.
> 
> @Skeltek Is there any formal lore/back that supports your "shield penetration" statement?

It has always been like that and known. The entry in the excell sheet 'damageNoArmourNoShield' is not used anywhere else. They would not make the effort to implement the entry and mechanics, if it was not going to be used for at least one unit in the game. It has always been accepted as an intentional feature.
Also it is described in the manual like that I think.

> Crion: Rumours abound of a top secret LC vehicle equipped with a deadly new energy weapon that is not stopped by shields or armour. This specialty unit can only carry a Plasma Artillery Cannon. The cannon can only be researched after the heavy electro and heavy sonic cannons. I is worth the wait.
https://luke2840.tripod.com/lc-units.htm

**Comment by GvardianDLVII** [comment] 2021-03-22 17:42
Nice research @Skeltek 👍 

When it comes to the damage type - I agree that it is a feature, not a bug. It would be a bug if it was meant to be blocked by armour or shield, but the mentioned game files make it explicitly bypass both armour and shield. Screamer+platoon is a good example of a bug - it is something that was never intended to work that way. There is no info about platoon disabling screamer anywhere, and code analysis doesn't lead to any indication of that either (it even shows the opposite).

Nevertheless, if Crions and/or plasma art require some rebalancing I'm open to discuss it as a possible change/feature even if it was to include changing it's damage type. But when it comes to treating it as a bug, I do not agree.

**Comment by Skeltek** [comment] 2021-04-28 19:30
I am closing this issue as resolved to reduce the large number of oen issues. Should anyone still have something to add, we can reopen it any time.

**Closed by Skeltek** 2021-04-28 19:30 UTC
Labels: Feature Request
